version: '3.8'

services:
  stronghodl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stronghodl-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:../stronghodl.db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-WFBKJWQSANFKNLWQNkwnqfwkqn!!#@932981nffnwq9h3FNIWFNEWF)}
    volumes:
      # Persist database and uploads (entire app directory)
      - stronghodl_data:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stronghodl-network

volumes:
  stronghodl_data:
    driver: local

networks:
  stronghodl-network:
    driver: bridge 